# ───── YAML ANCHORS FOR COMMON SETTINGS ─────
# Anchor for application services that share env_file and restart policy
x-app-defaults: &app-defaults
  restart: always
  env_file:
    - .env

networks:
  default:
    name: tankctl
    external: true


services:
  db:
    <<: *app-defaults
    image: postgres:14
    container_name: tankctl_postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:                 # 🆕 Add healthcheck here
      test: ["CMD", "pg_isready", "-U", "postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  redis:
    <<: *app-defaults
    image: redis:7
    container_name: tankctl_redis
    ports:
      - "6379:6379"

  web:
    build: .
    container_name: tankctl_fastapi
    <<: *app-defaults
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis
    command: >
      sh -c "sleep 10 && uvicorn app.main:app --host 0.0.0.0 --port 8000"

  celery_worker:
    build:
      context: .
      dockerfile: Dockerfile
    <<: *app-defaults
    command: celery -A app.worker.celery_app worker --loglevel=info
    depends_on:
      - redis
      - db
  
  celery_beat:
    build: .
    <<: *app-defaults
    depends_on:
      - web
      - db
      - redis
    command: celery -A app.worker.celery_app beat --loglevel=info

  grafana:
    image: grafana/grafana-oss:12.0.0
    <<: *app-defaults
    container_name: tankctl_grafana
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - "GF_PLUGINS_PREINSTALL=yesoreyeram-infinity-datasource, volkovlabs-form-panel"
    volumes:
      - ./docker/grafana/data:/var/lib/grafana
      - ./docker/grafana/provisioning:/etc/grafana/provisioning
      - ./docker/grafana/dashboards:/var/lib/grafana/dashboards  # ✅ ADD THIS LINE
      - ./docker/grafana/plugins:/var/lib/grafana/plugins  # ✅ ADD THIS LINE
    depends_on:
      - db

  prometheus:
    image: prom/prometheus:latest
    <<: *app-defaults
    container_name: tankctl_prometheus
    volumes:
      - ./docker/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"

  flower:
    build: .
    <<: *app-defaults
    container_name: tankctl_flower
    ports:
      - "5555:5555"
    command: celery -A app.worker.celery_app flower --port=5555
    depends_on:
      - redis
      - celery_worker
      - celery_beat

  cloudflared:
      restart: unless-stopped
      image: cloudflare/cloudflared:latest
      command: tunnel --no-autoupdate run --token
          eyJhIjoiMjc3OGFiNGIyMjVkOTQ0NWQ1MTY1ODNjMTU4OTQ5MWUiLCJ0IjoiNzliNTFkOTAtOGU3NS00NjZhLWJhMjctM2JhZGQ3ODU3ODlkIiwicyI6Ik1ETmpOV1ptWVRVdFlXTm1ZUzAwTlRZeUxUbGpNR1V0TkRnNVpEUXhZV1ZoTVRrNCJ9


volumes:
  postgres_data:
