version: "3.9"

services:
  db:
    image: postgres:14
    restart: always
    container_name: aquapi_postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:7
    restart: always
    container_name: aquapi_redis
    ports:
      - "6379:6379"

  web:
    build: .
    container_name: aquapi_fastapi
    restart: always
    env_file:
      - .env
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis
    command: >
      sh -c "sleep 10 && uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload"

  celery_worker:
    build:
      context: .
      dockerfile: Dockerfile
    command: celery -A app.worker.celery_app worker --beat --loglevel=info
    env_file:
      - .env
    depends_on:
      - redis
      - db


volumes:
  postgres_data:
