"""
Pydantic schemas for TankCtl API.

All schemas use strict validation with type checking and constraints.
"""

from pydantic import BaseModel, Field, field_validator
from typing import Optional, Dict, Literal


# ============================================================================
# Device Management Schemas
# ============================================================================

class DeviceRegisterRequest(BaseModel):
    """Request to register a new device."""
    
    model_config = {"str_strip_whitespace": True}

    device_id: str = Field(
        ...,
        min_length=1,
        max_length=100,
        pattern=r"^[a-zA-Z0-9_-]+$",
        description="Device identifier (alphanumeric, underscore, hyphen only)",
        examples=["tank1", "greenhouse-pump", "sensor_01"]
    )
    device_secret: str = Field(
        ...,
        min_length=8,
        max_length=256,
        description="Device authentication secret"
    )


class DeviceResponse(BaseModel):
    """Device response model."""

    device_id: str
    status: Literal["online", "offline"]
    firmware_version: Optional[str] = None
    created_at: Optional[str] = None
    last_seen: Optional[str] = None


# ============================================================================
# Command Schemas
# ============================================================================

class CommandRequest(BaseModel):
    """
    Request to send a command to device.
    
    Version is auto-generated by the backend and should NOT be provided.
    """
    
    model_config = {"str_strip_whitespace": True}

    command: str = Field(
        ...,
        min_length=1,
        max_length=50,
        pattern=r"^[a-z_]+$",
        description="Command name (lowercase, underscores only)",
        examples=["set_light", "set_pump", "reboot_device", "request_status"]
    )
    value: Optional[str] = Field(
        None,
        max_length=100,
        description="Command parameter value"
    )


class CommandResponse(BaseModel):
    """Command response model."""

    command_id: Optional[str] = None
    device_id: str
    command: str
    value: Optional[str] = None
    version: int
    status: Literal["pending", "sent", "executed", "failed", "timeout"]
    created_at: Optional[str] = None


# ============================================================================
# Convenience Endpoint Schemas
# ============================================================================

class LightStateRequest(BaseModel):
    """Request to set light state."""
    
    model_config = {"str_strip_whitespace": True}

    state: Literal["on", "off"] = Field(
        ...,
        description="Light state (on or off)"
    )


class PumpStateRequest(BaseModel):
    """Request to set pump state."""
    
    model_config = {"str_strip_whitespace": True}

    state: Literal["on", "off"] = Field(
        ...,
        description="Pump state (on or off)"
    )


# ============================================================================
# Device Shadow Schemas
# ============================================================================

class DeviceShadowUpdateRequest(BaseModel):
    """Request to update device shadow desired state."""

    desired: Dict[str, str] = Field(
        ...,
        description="Desired device state as key-value pairs",
        examples=[
            {"light": "on", "pump": "off"},
            {"temperature_threshold": "25"}
        ]
    )
    
    @field_validator("desired")
    @classmethod
    def validate_desired(cls, v: Dict[str, str]) -> Dict[str, str]:
        """Validate desired state dictionary."""
        if not v:
            raise ValueError("desired state cannot be empty")
        if len(v) > 50:
            raise ValueError("too many keys in desired state (max 50)")
        for key, value in v.items():
            if not isinstance(key, str) or not isinstance(value, str):
                raise ValueError("desired state must contain string keys and values")
            if len(key) > 50 or len(value) > 100:
                raise ValueError("keys/values too long")
        return v


class DeviceShadowResponse(BaseModel):
    """Device shadow response model."""

    device_id: str
    desired: Dict[str, str]
    reported: Dict[str, str]
    version: int = Field(..., ge=0, description="Shadow version number")
    synchronized: bool = Field(
        ...,
        description="True if desired and reported states match"
    )


# ============================================================================
# Health Check Schema
# ============================================================================

class HealthResponse(BaseModel):
    """Health check response."""

    status: Literal["healthy", "unhealthy", "degraded"]
    message: str
